-- Migration: Add practiceq_generated_google_meet column to appointments table
-- Date: November 11, 2025
-- Purpose: Store Google Meet links generated by PracticeQ/IntakeQ
--
-- CONTEXT:
-- PracticeQ (IntakeQ) automatically generates Google Meet links for telehealth
-- appointments via their Google Calendar integration. However, these links are
-- NOT exposed via the IntakeQ API, so we cannot retrieve them during sync.
--
-- SOLUTION:
-- Add a column to manually store PracticeQ-generated Google Meet links.
-- This will be populated via UI when creating/editing appointments.
--
-- FIELD USAGE:
-- - practiceq_generated_google_meet: Google Meet URL from PracticeQ
-- - meeting_url (existing): Our own generated Google Meet link
--
-- Both fields can coexist:
-- - PracticeQ link: Visible in IntakeQ, sent in patient notifications
-- - Our link: Stored in DB, visible in dashboards, backup if PracticeQ fails
--
-- ============================================================================
-- Add column to appointments table
-- ============================================================================

ALTER TABLE appointments
ADD COLUMN IF NOT EXISTS practiceq_generated_google_meet TEXT;

-- Add comment for documentation
COMMENT ON COLUMN appointments.practiceq_generated_google_meet IS
'Google Meet link generated by PracticeQ/IntakeQ (not accessible via API). Manually populated via UI at appointment creation time.';

-- ============================================================================
-- Verification
-- ============================================================================

-- Check column was added
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'appointments'
  AND column_name = 'practiceq_generated_google_meet';

-- Expected result:
-- column_name: practiceq_generated_google_meet
-- data_type: text
-- is_nullable: YES
-- column_default: NULL

-- ============================================================================
-- Notes
-- ============================================================================

-- Future work:
-- 1. Build UI component to add PracticeQ Google Meet link at appointment creation
-- 2. Display this link in appointment detail views
-- 3. Consider adding validation to ensure URL format is valid Google Meet link
-- 4. May want to sync this to patient notification emails if available
